<xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE libro SYSTEM “libro.dtd”
<carta xmlns:xsi=”http://www.w3.org/2001/XMLSchema-instance” 
            xsi:noNamespaceSchemaLocation=libro.xsd”>
 -->
<!DOCTYPE libro [
  <!ELEMENT libro (titulo, autor, editorial, anio_publicacion, genero, sinopsis)>
  <!ELEMENT titulo (#PCDATA)>
  <!ELEMENT autor (#PCDATA)>
  <!ELEMENT editorial (#PCDATA)>
  <!ELEMENT anio_publicacion (#PCDATA)>
  <!ELEMENT genero (#PCDATA)>
  <!ELEMENT sinopsis (#PCDATA)>
    ]>
    <libro>
  <titulo>El Principito</titulo>
  <autor>Antoine de Saint-Exupéry</autor>
  <editorial>Reynal & Hitchcock</editorial>
  <anio_publicacion>1943</anio_publicacion>
  <genero>Ficción</genero>
  <sinopsis>Un piloto se encuentra con un pequeño príncipe
   que viaja de planeta en planeta, aprendiendo lecciones 
   sobre la vida y la amistad</sinopsis>
</libro>
